# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nirs.ui'
#
# Created: Fri Mar 04 12:28:30 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(938, 580)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../images/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.new_2 = QtGui.QPushButton(self.centralwidget)
        self.new_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.new_2.setAutoDefault(False)
        self.new_2.setDefault(False)
        self.new_2.setFlat(False)
        self.new_2.setObjectName(_fromUtf8("new_2"))
        self.horizontalLayout_7.addWidget(self.new_2)
        self.run = QtGui.QPushButton(self.centralwidget)
        self.run.setObjectName(_fromUtf8("run"))
        self.horizontalLayout_7.addWidget(self.run)
        self.pause = QtGui.QPushButton(self.centralwidget)
        self.pause.setObjectName(_fromUtf8("pause"))
        self.horizontalLayout_7.addWidget(self.pause)
        self.stop = QtGui.QPushButton(self.centralwidget)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.horizontalLayout_7.addWidget(self.stop)
        self.setting = QtGui.QPushButton(self.centralwidget)
        self.setting.setObjectName(_fromUtf8("setting"))
        self.horizontalLayout_7.addWidget(self.setting)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(210, 38))
        self.dockWidget_3.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.dockWidget_3.setObjectName(_fromUtf8("dockWidget_3"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setEnabled(True)
        self.dockWidgetContents_3.setAcceptDrops(False)
        self.dockWidgetContents_3.setAccessibleName(_fromUtf8(""))
        self.dockWidgetContents_3.setAutoFillBackground(False)
        self.dockWidgetContents_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.layoutWidget = QtGui.QWidget(self.dockWidgetContents_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 156, 20))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gain1_label = QtGui.QLabel(self.layoutWidget)
        self.gain1_label.setObjectName(_fromUtf8("gain1_label"))
        self.horizontalLayout.addWidget(self.gain1_label)
        self.gain1_combo = QtGui.QComboBox(self.layoutWidget)
        self.gain1_combo.setMaxVisibleItems(10)
        self.gain1_combo.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.gain1_combo.setFrame(False)
        self.gain1_combo.setObjectName(_fromUtf8("gain1_combo"))
        self.horizontalLayout.addWidget(self.gain1_combo)
        self.layoutWidget1 = QtGui.QWidget(self.dockWidgetContents_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 156, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gain2_label = QtGui.QLabel(self.layoutWidget1)
        self.gain2_label.setObjectName(_fromUtf8("gain2_label"))
        self.horizontalLayout_5.addWidget(self.gain2_label)
        self.gain2_combo = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gain2_combo.setFont(font)
        self.gain2_combo.setIconSize(QtCore.QSize(16, 16))
        self.gain2_combo.setObjectName(_fromUtf8("gain2_combo"))
        self.gain2_combo.addItem(_fromUtf8(""))
        self.gain2_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.gain2_combo)
        self.layoutWidget2 = QtGui.QWidget(self.dockWidgetContents_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 220, 191, 261))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget2)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.slider_730 = QtGui.QSlider(self.groupBox)
        self.slider_730.setGeometry(QtCore.QRect(20, 30, 19, 160))
        self.slider_730.setProperty("value", 25)
        self.slider_730.setOrientation(QtCore.Qt.Vertical)
        self.slider_730.setObjectName(_fromUtf8("slider_730"))
        self.value_730 = QtGui.QLabel(self.groupBox)
        self.value_730.setGeometry(QtCore.QRect(40, 180, 46, 13))
        self.value_730.setObjectName(_fromUtf8("value_730"))
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget2)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.slider_850 = QtGui.QSlider(self.groupBox_2)
        self.slider_850.setGeometry(QtCore.QRect(10, 30, 19, 160))
        self.slider_850.setProperty("value", 25)
        self.slider_850.setOrientation(QtCore.Qt.Vertical)
        self.slider_850.setObjectName(_fromUtf8("slider_850"))
        self.value_850 = QtGui.QLabel(self.groupBox_2)
        self.value_850.setGeometry(QtCore.QRect(30, 180, 46, 13))
        self.value_850.setObjectName(_fromUtf8("value_850"))
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_3)
        self.comboBox.setGeometry(QtCore.QRect(28, 150, 101, 51))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.actionNew_Ctrl_N = QtGui.QAction(MainWindow)
        self.actionNew_Ctrl_N.setCheckable(False)
        self.actionNew_Ctrl_N.setVisible(True)
        self.actionNew_Ctrl_N.setObjectName(_fromUtf8("actionNew_Ctrl_N"))
        self.actionSave_Ctrl_S = QtGui.QAction(MainWindow)
        self.actionSave_Ctrl_S.setObjectName(_fromUtf8("actionSave_Ctrl_S"))
        self.actionQuit_Ctrl_Q = QtGui.QAction(MainWindow)
        self.actionQuit_Ctrl_Q.setObjectName(_fromUtf8("actionQuit_Ctrl_Q"))
        self.actionRun_Ctrl_R = QtGui.QAction(MainWindow)
        self.actionRun_Ctrl_R.setObjectName(_fromUtf8("actionRun_Ctrl_R"))
        self.actionPause_Ctrl_P = QtGui.QAction(MainWindow)
        self.actionPause_Ctrl_P.setObjectName(_fromUtf8("actionPause_Ctrl_P"))
        self.actionStop_Ctrl_F = QtGui.QAction(MainWindow)
        self.actionStop_Ctrl_F.setObjectName(_fromUtf8("actionStop_Ctrl_F"))
        self.actionSetting = QtGui.QAction(MainWindow)
        self.actionSetting.setObjectName(_fromUtf8("actionSetting"))
        self.menuFile.addAction(self.actionNew_Ctrl_N)
        self.menuFile.addAction(self.actionSave_Ctrl_S)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_Ctrl_Q)
        self.menuRun.addAction(self.actionRun_Ctrl_R)
        self.menuRun.addAction(self.actionPause_Ctrl_P)
        self.menuRun.addAction(self.actionStop_Ctrl_F)
        self.menuSetting.addAction(self.actionSetting)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.gain1_combo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Nirs", None))
        self.new_2.setText(_translate("MainWindow", "New", None))
        self.run.setText(_translate("MainWindow", "Run", None))
        self.pause.setText(_translate("MainWindow", "Pause", None))
        self.stop.setText(_translate("MainWindow", "Stop", None))
        self.setting.setText(_translate("MainWindow", "Setting", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.gain1_label.setText(_translate("MainWindow", "Gain Detector 1", None))
        self.gain2_label.setText(_translate("MainWindow", "Gain Detector 2", None))
        self.gain2_combo.setItemText(0, _translate("MainWindow", "1", None))
        self.gain2_combo.setItemText(1, _translate("MainWindow", "2", None))
        self.groupBox.setTitle(_translate("MainWindow", "730 (nm)", None))
        self.value_730.setText(_translate("MainWindow", "730 (nm)", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "850 (nm)", None))
        self.value_850.setText(_translate("MainWindow", "730 (nm)", None))
        self.actionNew_Ctrl_N.setText(_translate("MainWindow", "New        Ctrl+N", None))
        self.actionSave_Ctrl_S.setText(_translate("MainWindow", "Save        Ctrl+S", None))
        self.actionQuit_Ctrl_Q.setText(_translate("MainWindow", "Quit        Ctrl+Q", None))
        self.actionRun_Ctrl_R.setText(_translate("MainWindow", "Run        Ctrl+R", None))
        self.actionPause_Ctrl_P.setText(_translate("MainWindow", "Pause        Ctrl+P", None))
        self.actionStop_Ctrl_F.setText(_translate("MainWindow", "Stop        Ctrl+F", None))
        self.actionSetting.setText(_translate("MainWindow", "Setting", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

